baseURL = "https://grundleborg.github.io/"
languageCode = "en-gb"
title = "Grundleborg's Cave"

googleAnalytics = "UA-30877098-2"

theme = "hyde"

[params]
  themeColor = "theme-base-0b"
  description = "Ramblings about Software Development, Hardware Hacking, Cinema & Trains."
